apiVersion: 1

datasources:
  - name: Yandex Prometheus Workspace
    type: prometheus
    access: proxy
    url: https://monitoring.api.cloud.yandex.net/prometheus/workspaces/monhr2m0jl118pvk9mtu/api/v1
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    secureJsonData:
      httpHeaderValue1: "Bearer ${PROMETHEUS_API_KEY}"
    version: 1
    uid: prometheus-workspace
