apiVersion: 1

datasources:
  - name: Yandex Prometheus Workspace
    type: prometheus
    access: proxy
    url: https://monitoring.api.cloud.yandex.net/prometheus/workspaces/monhr2m0jl118pvk9mtu/api/v1
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: ${PROMETHEUS_API_KEY}
    version: 1
    uid: prometheus-workspace
